# -*- coding: utf-8 -*-
"""Proyecto Final Tuberculosis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bg8tH-tYtin7JTc8LaIEeCZldxKVx82E

#Análisis de Tubercolosis

###**Cargar los datos**
"""

#Paquetes para manipular datos
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

#Paquetes para conectarse a Google Drive
from google.colab import drive
drive.mount('/content/drive')

#Csv population
pop = pd.read_csv("/content/drive/MyDrive/Data/population.csv")
pop.head()

# Csv who
who = pd.read_csv("/content/drive/MyDrive/Data/who.csv")
who.head()

who.head(100)

"""## Análisis teórico tuberculosis

###Tuberculosis: Revisón general de una enfermedad infecciosa de impacto global.

Revista Médica de Revisión | Volumen 12, 2025

##RESUMEN
La tuberculosis (TB) es una enfermedad infecciosa crónica causada por Mycobacterium tuberculosis, que constituye una de las principales causas de morbimortalidad a nivel mundial. A pesar de los avances diagnósticos y terapéuticos, la TB continúa representando un desafío de salud pública de primera magnitud, especialmente en países de ingresos bajos y medios. Este artículo revisa de forma exhaustiva la epidemiología, etiopatogenia, manifestaciones clínicas, diagnóstico, tratamiento, prevención y perspectivas futuras de esta enfermedad.
Palabras clave: Tuberculosis, Mycobacterium tuberculosis, salud pública, infección latente, resistencia antimicrobiana.

##1. INTRODUCCIÓN
La tuberculosis es una de las enfermedades infecciosas más antiguas que han afectado a la humanidad. Evidencias paleopatológicas sugieren su presencia en restos óseos del Neolítico, y referencias a la tisis (término clásico para la TB pulmonar) se encuentran en escritos hipocráticos del siglo V a.C. (Bates & Stead, 1993). No obstante, fue Robert Koch quien, en 1882, identificó formalmente al agente causal —denominado entonces Bacillus tuberculosis— en un hito que transformó la comprensión de las enfermedades infecciosas (Koch, 1882).
Durante el siglo XX, la introducción de la vacuna BCG (1921), el descubrimiento de la estreptomicina (1943) y la isoniazida (1952) redujeron drásticamente la mortalidad en países industrializados. Sin embargo, la pandemia de VIH/SIDA, la emergencia de cepas resistentes y la desigualdad en el acceso a la atención médica han mantenido a la TB como un problema de salud pública global de primer orden (WHO, 2023).

##2. EPIDEMIOLOGÍA
2.1 Situación global
De acuerdo con el Informe Global sobre Tuberculosis de la Organización Mundial de la Salud (OMS), en 2022 se estimaron aproximadamente 10,6 millones de nuevos casos de TB en el mundo, con una tasa de incidencia de 133 por 100.000 habitantes. La enfermedad causó cerca de 1,3 millones de muertes, incluyendo 167.000 en personas con coinfección por VIH (WHO, 2023).
Las regiones con mayor carga son Asia Sudoriental, África y el Pacífico Occidental, que concentran juntas más del 80% de los casos globales. Los ocho países con mayor incidencia —India, Indonesia, China, Filipinas, Pakistán, Nigeria, Bangladesh y la República Democrática del Congo— representan aproximadamente dos tercios del total mundial (WHO, 2023).
2.2 Factores de riesgo
Los principales factores de riesgo para el desarrollo de TB activa incluyen:

Infección por VIH: incrementa el riesgo de progresión de infección latente a enfermedad activa entre 20 y 37 veces (Lawn & Zumla, 2011).
Desnutrición: el riesgo poblacional atribuible es de aproximadamente 26,7% (WHO, 2023).
Diabetes mellitus: multiplica por tres el riesgo de enfermedad activa (Jeon & Murray, 2008).
Tabaquismo y consumo de alcohol: asociados a mayor incidencia y peores desenlaces.
Hacinamiento y pobreza: determinantes estructurales fundamentales.
Inmunosupresión farmacológica: uso de corticosteroides, anti-TNF-α u otros agentes biológicos.
Silicosis y otras neumoconiosis.

2.3 TB resistente a fármacos
Un desafío creciente es la TB multirresistente (TB-MDR), definida como resistencia al menos a rifampicina e isoniazida, los dos fármacos de primera línea más potentes. En 2022, se registraron aproximadamente 410.000 casos de TB-MDR/TB resistente a rifampicina (TB-RR), con apenas el 57% de éxito terapéutico. La TB extremadamente resistente (TB-XDR) —resistente también a fluoroquinolonas y al menos un fármaco inyectable de segunda línea— presenta tasas de curación aún más limitadas (WHO, 2023).

##3. ETIOLOGÍA Y MICROBIOLOGÍA
3.1 El agente causal
Mycobacterium tuberculosis pertenece al complejo M. tuberculosis (CMTB), que incluye también a M. bovis, M. africanum, M. microti y otras especies menos frecuentes. Es un bacilo aerobio estricto, no esporulado, inmóvil y de crecimiento lento —con un tiempo de duplicación de 15 a 20 horas— que se tiñe mediante la técnica de Ziehl-Neelsen como bacilo ácido-alcohol resistente (BAAR), dada su pared celular rica en ácidos micólicos (Murray et al., 2021).
3.2 Composición de la pared celular
La pared celular de M. tuberculosis es extraordinariamente compleja y desempeña un papel central en su patogenicidad. Está compuesta por:

Ácidos micólicos: lípidos de cadena larga que confieren hidrofobicidad y resistencia a la fagocitosis.
Arabinogalactano y peptidoglicano: forman el armazón estructural.
Lipoarabinomanano (LAM): glucolípido con potentes propiedades inmunomoduladoras que inhibe la activación de macrófagos.
Sulfolípidos y cord factor (trehalosa dimicolato): contribuyen a la virulencia y la supervivencia intracelular.

Esta composición única explica la resistencia del microorganismo a muchos antibióticos convencionales, a la desecación y a ciertos desinfectantes (Brennan & Nikaido, 1995).

##4. PATOGENIA E INMUNOLOGÍA
4.1 Transmisión
La TB pulmonar se transmite fundamentalmente por vía aerógena. Las partículas de Wells o droplet nuclei —gotículas de menos de 5 µm generadas al toser, estornudar, hablar o cantar un paciente con TB pulmonar activa— permanecen suspendidas en el aire durante horas y pueden alcanzar los alvéolos pulmonares (Riley et al., 1962). Un enfermo no tratado puede infectar entre 10 y 15 personas por año.
4.2 Infección primaria y respuesta inmune
Al llegar al alveolo, los bacilos son fagocitados por macrófagos alveolares. M. tuberculosis posee múltiples mecanismos para evadir la respuesta inmune innata:

Inhibición de la fusión fagosoma-lisosoma mediante la retención de fosfatidilositol-3-fosfato.
Supresión de la apoptosis del macrófago infectado.
Modulación de la respuesta al interferón.
Resistencia al estrés oxidativo mediante enzimas como la catalasa-peroxidasa.

La respuesta inmune adaptativa, coordinada por linfocitos T CD4⁺ (Th1), produce interferón gamma (IFN-γ) y TNF-α, que activan a los macrófagos para eliminar los bacilos y formar el granuloma (Cooper, 2009).
4.3 El granuloma tuberculoso
El granuloma es la estructura anatómica central de la TB. Es un agregado organizado de macrófagos activados —que se transforman en células epitelioides y células gigantes de Langhans— rodeados por linfocitos T y B. Su función es contener pero no siempre eliminar al bacilo. En la zona central del granuloma maduro se forma la necrosis caseosa, material sólido de aspecto similar al queso que contiene bacilos viables en estado de latencia metabólica (Russell, 2007).
Cuando la inmunidad del huésped es suficiente, el granuloma se calcifica formando el foco de Ghon, que junto con la adenopatía hiliar ipsilateral constituye el complejo de Ranke, evidenciable radiológicamente.
4.4 Reactivación y progresión a enfermedad activa
En aproximadamente el 90% de los inmunocompetentes infectados, el sistema inmune logra contener la infección en un estado latente (ILTB). Sin embargo, el 5-10% desarrollará TB activa a lo largo de su vida, con mayor riesgo en los primeros 2 años tras la infección primaria. Condiciones que deterioran la inmunidad celular favorecen la reactivación: infección por VIH, malnutrición, diabetes, neoplasias, terapia inmunosupresora y envejecimiento fisiológico (Dye et al., 1999).

##5. CLASIFICACIÓN Y MANIFESTACIONES CLÍNICAS
5.1 Infección tuberculosa latente (ILTB)
La ILTB se define como un estado de respuesta inmune persistente a los antígenos de M. tuberculosis sin evidencia de enfermedad activa. El paciente está asintomático, no es contagioso y presenta prueba de tuberculina (PPD) o IGRA positivos. Se estima que cerca de un cuarto de la población mundial tiene ILTB (Houben & Dodd, 2016).
5.2 TB pulmonar activa (forma más frecuente)
La TB pulmonar representa el 80-85% de todos los casos y constituye la forma contagiosa. La presentación clínica clásica incluye:

Síntomas constitucionales: fiebre vespertina, sudoración nocturna, pérdida de peso y astenia progresiva (de ahí el término histórico "fiebre consúntica").
Tos: inicialmente seca, progresa a productiva con esputo mucopurulento. Presente en más del 90% de los casos.
Hemoptisis: desde esputo hemoptoico hasta hemoptisis masiva por erosión de vasos pulmonares; es un signo de alarma.
Dolor pleurítico: cuando existe pleuritis asociada.
Disnea: en enfermedad avanzada, derrame pleural o neumotórax espontáneo.

El curso es subagudo o crónico, generalmente de semanas a meses de evolución antes del diagnóstico, lo que favorece la transmisión comunitaria.
5.3 TB extrapulmonar
La TB extrapulmonar (TBEP) constituye el 15-20% de los casos en inmunocompetentes y hasta el 50% en pacientes con VIH avanzado. Las formas más relevantes son:
TB ganglionar (linfadenopatía tuberculosa)
Es la forma extrapulmonar más frecuente. Se manifiesta como adenopatías cervicales, supraclaviculares o axilares, de consistencia firme, inicialmente indoloras, que pueden fistulizar a la piel (escrofulodermia). El diagnóstico se confirma mediante biopsia ganglionar (Fontanilla et al., 2011).
TB pleural
Segunda forma extrapulmonar más común. Se presenta como derrame pleural exudativo unilateral, linfocítico, con adenosina deaminasa (ADA) elevada (>40 UI/L). Puede ser la manifestación inicial de una primoinfección o de reactivación.
TB meníngea
La más grave de todas las formas. Presenta una triada clásica de cefalea, fiebre y alteración del nivel de conciencia. El LCR muestra pleocitosis linfocítica, hipoglucorraquia, hiperproteinorraquia y presión elevada. La mortalidad sin tratamiento se aproxima al 100%; incluso con tratamiento, puede superar el 30% (Thwaites et al., 2009).
TB miliar
Diseminación hematógena masiva con siembra generalizada. En la radiografía de tórax se observa el patrón miliar clásico: nódulos de 1-3 mm distribuidos difusamente en ambos campos pulmonares, como "semillas de mijo". Puede afectar simultáneamente pulmón, hígado, bazo, médula ósea, meninges y coroides (signo de Brömel).
TB osteoarticular
El mal de Pott es la forma vertebral, que afecta preferentemente la columna torácica baja y lumbar. Produce destrucción del cuerpo vertebral, cifosis angular (giba), absceso frío paravertebral y puede comprimir la médula espinal causando paraplejia.
TB genitourinaria
Puede afectar riñones, uréteres, vejiga y tracto genital. Causa hematuria, piuria estéril, hidronefrosis y, en mujeres, infertilidad por salpingitis tuberculosa crónica.
TB pericárdica
Se presenta como pericarditis exudativa y puede evolucionar a pericarditis constrictiva crónica con compromiso hemodinámico grave.

##6. DIAGNÓSTICO
6.1 Diagnóstico de infección latente
Prueba de tuberculina (PPD/Mantoux)
Consiste en la inyección intradérmica de 0,1 mL (2 UT) de derivado proteínico purificado de M. tuberculosis. La lectura se realiza a las 48-72 horas midiendo la induración (no el eritema). Se considera positiva cuando la induración es ≥10 mm en población general, ≥5 mm en inmunocomprometidos o contactos recientes de TB activa.
Limitaciones: Puede ser falsamente negativa en inmunosuprimidos, TB miliar o meníngea ("anergia tuberculínica"). Presenta reacciones cruzadas con la vacuna BCG y con micobacterias no tuberculosas (MNT).
Ensayos de liberación de interferón gamma (IGRA)
Son pruebas in vitro que miden la producción de IFN-γ por linfocitos T sensibilizados ante antígenos específicos de M. tuberculosis (ESAT-6, CFP-10). Existen dos plataformas comerciales aprobadas: QuantiFERON-TB Gold Plus (QFT-Plus) y T-SPOT.TB. Son más específicas que el PPD al no verse afectadas por la vacunación BCG (Pai et al., 2014).
6.2 Diagnóstico de enfermedad activa
Baciloscopía (Ziehl-Neelsen / fluorescencia)
La microscopía directa del esputo mediante tinción de Ziehl-Neelsen o auramina-rodamina es la técnica más accesible en entornos de bajos recursos. Detecta BAAR con una sensibilidad del 40-60% y especificidad variable. Requiere al menos 5.000-10.000 bacilos/mL de muestra para ser positiva. Se recomienda el análisis de tres muestras matutinas en días consecutivos.
Cultivo micobacteriológico
Es el estándar de oro diagnóstico. Permite la identificación de especie y la realización de antibiograma. Los medios sólidos (Löwenstein-Jensen) tardan 3-8 semanas; los sistemas líquidos automatizados (MGIT 960, BacT/Alert) reducen el tiempo a 1-3 semanas. La sensibilidad supera el 80% en muestras respiratorias de pacientes con TB pulmonar (American Thoracic Society, 2000).
Técnicas moleculares
Representan el mayor avance diagnóstico reciente:

Xpert MTB/RIF (GeneXpert): PCR en tiempo real que detecta ADN de M. tuberculosis y resistencia a rifampicina en menos de 2 horas. Sensibilidad del 88% en baciloscopía positiva y 67% en negativa. Recomendado por la OMS como prueba diagnóstica inicial en países de alta carga (WHO, 2013).
Xpert MTB/RIF Ultra: versión mejorada con mayor sensibilidad, especialmente útil en muestras paucibacilares.
Test de línea reversa (LPA): detecta resistencia a isoniazida, rifampicina y fármacos de segunda línea.
Secuenciación de nueva generación (NGS): permite la caracterización exhaustiva del perfil de resistencia y el análisis filogenético.

Diagnóstico por imagen
La radiografía de tórax es fundamental. Los hallazgos clásicos de TB pulmonar activa incluyen:

Consolidaciones o infiltrados en lóbulos superiores y segmentos apicales.
Cavitación (patognomónica de TB secundaria activa).
Nódulos de Ghon calcificados (primoinfección curada).
Adenopatías hiliares o mediastínicas.
Derrame pleural.

La tomografía computarizada (TC) de alta resolución es más sensible y permite caracterizar mejor las lesiones, detectar cavitaciones pequeñas, linfadenopatías mediastínicas y patología extrapulmonar.
Diagnóstico anatomopatológico
En formas extrapulmonares, la biopsia del tejido afecto —ganglio, pleura, hueso, médula ósea— que muestre granulomas con necrosis caseosa y BAAR (o cultivo positivo) confirma el diagnóstico. La tinción de PAS y la de Wade-Fite pueden ser útiles.
Pruebas de función biológica
En TB pleural, la ADA en líquido pleural >40 UI/L tiene sensibilidad del 93% y especificidad del 90% para TB (Light, 2010). En TB meníngea, el LCR muestra glucosa <45 mg/dL, proteínas >100 mg/dL y ADA elevada.

##7. TRATAMIENTO
7.1 Principios generales
El tratamiento de la TB se basa en tres principios fundamentales: utilizar múltiples fármacos para evitar la selección de mutantes resistentes, duración prolongada para erradicar la población bacilar en distintos estados metabólicos, y adherencia estricta para evitar el fracaso terapéutico y la resistencia adquirida (Mitchison, 1985).
7.2 Tratamiento de la TB sensible
El régimen estándar recomendado por la OMS para TB pulmonar en adultos con cepas sensibles consta de dos fases:
Fase intensiva (2 meses):
Isoniazida (H) + Rifampicina (R) + Pirazinamida (Z) + Etambutol (E)
Notación: 2HRZE
Fase de consolidación (4 meses):
Isoniazida (H) + Rifampicina (R)
Notación: 4HR
El régimen completo se expresa como 2HRZE/4HR y tiene tasas de curación superiores al 90% en pacientes adherentes (WHO, 2022).
Dosis en adultos (peso 50-70 kg):

Isoniazida: 5 mg/kg/día (máx. 300 mg/día)
Rifampicina: 10 mg/kg/día (máx. 600 mg/día)
Pirazinamida: 25 mg/kg/día (máx. 2.000 mg/día)
Etambutol: 15-20 mg/kg/día (máx. 1.600 mg/día)

En TB meníngea, osteoarticular y pericárdica, la duración total se extiende a 9-12 meses.
7.3 Nuevos regímenes acortados
Estudios recientes han evaluado regímenes de menor duración. El ensayo STREAM Stage 2 y el régimen TB-PRACTECAL han demostrado eficacia con tratamientos de 4-6 meses basados en bedaquilina, pretomanida y linezolid para TB-MDR (Nunn et al., 2019). Para TB sensible, el régimen de 4 meses con rifapentina y moxifloxacino (ensayo TBTC S31/ACTG A5349) mostró no inferioridad frente al régimen de 6 meses en análisis recientes (Dorman et al., 2021).
7.4 Efectos adversos principales

Isoniazida: hepatotoxicidad (5-10%), neuropatía periférica (por déficit de piridoxina; se previene con vitamina B₆), psicosis.
Rifampicina: hepatotoxicidad, síndrome gripal, coloración naranja de secreciones, numerosas interacciones farmacológicas por inducción del citocromo P450 (CYP3A4).
Pirazinamida: hepatotoxicidad (la más frecuente), hiperuricemia, artralgias.
Etambutol: neuritis óptica retrobulbar (reversible si se detecta precozmente), monitorizar agudeza visual y visión de colores mensualmente.

7.5 Tratamiento de la infección tuberculosa latente
El tratamiento de la ILTB en personas con alto riesgo de progresión reduce la incidencia de TB activa en un 60-90%. Los regímenes actuales incluyen:

6H: isoniazida durante 6 meses (eficacia ~60-70%).
9H: isoniazida durante 9 meses (eficacia ~90%; estándar en EE.UU. y OPS).
3HP: rifapentina semanal + isoniazida durante 3 meses (comparable eficacia a 9H con mejor adherencia).
1HP: rifapentina + isoniazida diaria durante 1 mes (ensayo BRIEF TB; no inferior a 9H).
4R: rifampicina durante 4 meses (mejor tolerancia hepática que isoniazida).

7.6 Tratamiento de la TB-MDR y TB-XDR
Desde 2019, la OMS recomienda regímenes totalmente orales para TB-MDR. El régimen BPaL (bedaquilina + pretomanida + linezolid) mostró una tasa de éxito del 89% en TB-XDR en el ensayo ZeNix (Conradie et al., 2022). La bedaquilina y la delamanida son los únicos nuevos fármacos con mecanismos de acción novedosos (inhibición de la ATP-sintasa micobacteriana y de la síntesis de ácidos micólicos, respectivamente) aprobados para TB en las últimas décadas.
7.7 Tratamiento en poblaciones especiales

VIH/TB coinfección: iniciar tratamiento antituberculoso primero; el TARV se inicia a las 2-8 semanas (si CD4 <50/µL, iniciar TARV a las 2 semanas). Vigilar síndrome de reconstitución inmune (SRI).
Embarazo: los fármacos de primera línea son seguros. Evitar estreptomicina (ototoxicidad fetal). La pirazinamida se incluye en la mayoría de las guías actuales.
Insuficiencia renal: ajustar dosis de etambutol y pirazinamida.
Insuficiencia hepática: evitar o reducir dosis de isoniazida, rifampicina y pirazinamida según el grado de disfunción.
Niños: régimen similar al adulto, ajustado por peso. Dosis de isoniazida de 10 mg/kg/día.


##8. PREVENCIÓN Y CONTROL
8.1 Vacuna BCG
La vacuna de bacilo de Calmette y Guérin (BCG), elaborada con una cepa atenuada de M. bovis, fue desarrollada por Albert Calmette y Camille Guérin en el Instituto Pasteur de París, con la primera vacunación humana en 1921. Es la vacuna más ampliamente administrada en el mundo y forma parte del Programa Ampliado de Inmunización (PAI) de la OMS.
La BCG ofrece una protección elevada (70-80%) contra las formas graves de TB infantil —meningitis tuberculosa y TB miliar— pero su eficacia contra la TB pulmonar en adultos es variable (0-80% según estudios), hecho que permanece sin explicación definitiva y que puede relacionarse con la exposición previa a micobacterias ambientales (Fine, 1995).
8.2 Nuevas vacunas en desarrollo
Más de una decena de candidatos vacunales se encuentran en evaluación clínica. La vacuna MVA85A (subunidad de proteína de fusión) no mostró eficacia en un gran ensayo en lactantes sudafricanos (Tameris et al., 2013). Sin embargo, M72/AS01E ha mostrado resultados prometedores: en un ensayo fase IIb en adultos con ILTB en Kenya, Zambia y Sudáfrica, redujo la incidencia de TB activa en un 49,7% (Van Der Meeren et al., 2018), con seguimiento extendido que confirma la durabilidad de la respuesta. M72/AS01E está actualmente en ensayo de fase 3.
8.3 Estrategia End TB de la OMS
La Estrategia Fin a la TB (End TB), aprobada en 2014 para el período 2016-2035, establece metas ambiciosas: reducir las muertes por TB en un 90% y la incidencia en un 80% para 2030 respecto a 2015. Sus pilares son:

Atención y prevención integrada centrada en el paciente.
Políticas audaces y sistemas de apoyo (financiamiento, recursos humanos, acceso a fármacos).
Investigación e innovación intensificadas.

Los indicadores intermedios para 2020 y 2025 no se han alcanzado, en parte por el impacto de la pandemia de COVID-19, que provocó una reducción global en el diagnóstico y tratamiento de TB entre 2020 y 2021 (WHO, 2022).
8.4 Medidas de control de infección
Las medidas de control de infección TB en establecimientos de salud siguen una jerarquía de tres niveles:

Controles administrativos: identificación rápida de casos, separación de pacientes bacilíferos, reducción del tiempo de estancia, educación del personal.
Controles ambientales: ventilación natural o mecánica adecuada (≥12 cambios de aire/hora), luz ultravioleta germicida (UVGI), presión negativa en habitaciones de aislamiento.
Protección respiratoria personal: uso de respiradores N95 o FFP2 por el personal de salud al atender pacientes con TB confirmada o sospechada.


##9. TUBERCULOSIS Y VIH: LA SINDEMIA
La coinfección VIH-TB es el paradigma de la sindemia infecciosa. M. tuberculosis es la principal causa de muerte en personas con VIH, responsable de un cuarto de los fallecimientos atribuibles al VIH (WHO, 2023). El VIH deteriora la inmunidad celular, favorece la progresión de ILTB a TB activa, altera la presentación clínica (mayor frecuencia de formas extrapulmonares y diseminadas), y dificulta el diagnóstico (mayor tasa de baciloscopía negativa).
La integración de los servicios de TB y VIH —con prueba universal de VIH en todos los pacientes con TB y viceversa, inicio temprano de TARV, y profilaxis con trimetoprima-sulfametoxazol— ha demostrado reducir significativamente la mortalidad (Havlir et al., 2011).

##10. PERSPECTIVAS FUTURAS E INVESTIGACIÓN
10.1 Diagnóstico
La búsqueda de biomarcadores en sangre periférica capaces de distinguir TB activa, ILTB e individuos sanos constituye un área prioritaria. Firmas transcriptómicas basadas en la expresión de genes del huésped (como la firma de 16 genes de Berry et al., 2010, y el signature de Sweeney de 3 genes) prometen diagnósticos más accesibles y aplicables en entornos de bajos recursos. La inteligencia artificial y el aprendizaje automático están siendo aplicados al análisis de imágenes radiológicas para mejorar la sensibilidad diagnóstica (Qin et al., 2019).
10.2 Tratamiento
La biología de sistemas y el análisis genómico de alta resolución están identificando nuevos blancos terapéuticos en M. tuberculosis. El complejo enzimático de síntesis de la pared celular y el sistema de síntesis de ATP son dianas particularmente atractivas. La betaquilina, la delamanida y la pretomanida —todos aprobados después de 2012— representan la primera renovación de la farmacología antituberculosa en décadas.
Los ensayos clínicos en curso (TB-PRACTECAL, DELIBERATE, TRUNCATE-TB) exploran la posibilidad de tratamientos de 2-4 meses para TB sensible y MDR mediante combinaciones con fármacos repropuestos como el linezolid, el clofazimino y el carbapenems.
10.3 Erradicación: ¿es posible?
La TB cumple los criterios teóricos para la erradicación —solo infecta humanos en su forma relevante de salud pública, existe una prueba diagnóstica y un tratamiento curativo— pero la complejidad de la infección latente, la resistencia farmacológica, los determinantes sociales de la salud y la falta de inversión sostenida hacen que la erradicación siga siendo un horizonte lejano. Sin embargo, la eliminación (definida como <1 caso por millón de habitantes) es técnicamente alcanzable en países de alta renta con estrategias integradas (Dye et al., 2013).

##11. CONCLUSIONES
La tuberculosis continúa siendo uno de los mayores desafíos de la medicina y la salud pública global en el siglo XXI. A pesar de ser una enfermedad curable, millones de personas mueren anualmente por falta de diagnóstico oportuno, acceso a tratamiento, resistencia farmacológica y factores socioeconómicos estructurales. Los avances en biología molecular, farmacología e inmunología ofrecen perspectivas esperanzadoras, pero solo serán transformadores si se acompañan de voluntad política, inversión sostenida y reducción de las inequidades globales en salud. La meta de eliminar la TB como problema de salud pública para 2030 requiere un esfuerzo coordinado sin precedentes de los sistemas de salud, la comunidad científica y los gobiernos del mundo.

##REFERENCIAS
American Thoracic Society. (2000). Diagnostic standards and classification of tuberculosis in adults and children. American Journal of Respiratory and Critical Care Medicine, 161(4), 1376–1395. https://doi.org/10.1164/ajrccm.161.4.16141
Bates, J. H., & Stead, W. W. (1993). The history of tuberculosis as a global epidemic. Medical Clinics of North America, 77(6), 1205–1217.
Berry, M. P. R., Graham, C. M., McNab, F. W., Xu, Z., Bloch, S. A. A., Oni, T., … O'Garra, A. (2010). An interferon-inducible neutrophil-driven blood transcriptional signature in human tuberculosis. Nature, 466(7309), 973–977.
Brennan, P. J., & Nikaido, H. (1995). The envelope of mycobacteria. Annual Review of Biochemistry, 64, 29–63.
Conradie, F., Diacon, A. H., Ngubane, N., Howell, P., Everitt, D., Crook, A. M., … Spigelman, M. (2022). Treatment of highly drug-resistant pulmonary tuberculosis. New England Journal of Medicine, 387(9), 810–823.
Cooper, A. M. (2009). Cell-mediated immune responses in tuberculosis. Annual Review of Immunology, 27, 393–422.
Dorman, S. E., Nahid, P., Kurbatova, E. V., Phillips, P. P. J., Bryant, K., Dooley, K. E., … Johnson, J. L. (2021). Four-month rifapentine regimens with or without moxifloxacin for tuberculosis. New England Journal of Medicine, 384(18), 1705–1718.
Dye, C., Scheele, S., Dolin, P., Pathania, V., & Raviglione, M. C. (1999). Consensus statement: Global burden of tuberculosis. JAMA, 282(7), 677–686.
Dye, C., Glaziou, P., Floyd, K., & Raviglione, M. (2013). Prospects for tuberculosis elimination. Annual Review of Public Health, 34, 271–286.
Fine, P. E. M. (1995). Variation in protection by BCG: Implications of and for heterologous immunity. The Lancet, 346(8986), 1339–1345.
Fontanilla, J. M., Barnes, A., & von Reyn, C. F. (2011). Current diagnosis and management of peripheral tuberculous lymphadenitis. Clinical Infectious Diseases, 53(6), 555–562.
Havlir, D. V., Kendall, M. A., Ive, P., Kumwenda, J., Swindells, S., Qasba, S. S., … Sanne, I. (2011). Timing of antiretroviral therapy for HIV-1 infection and tuberculosis. New England Journal of Medicine, 365(16), 1482–1491.
Houben, R. M. G. J., & Dodd, P. J. (2016). The global burden of latent tuberculosis infection: A re-estimation using mathematical modelling. PLOS Medicine, 13(10), e1002152.
Jeon, C. Y., & Murray, M. B. (2008). Diabetes mellitus increases the risk of active tuberculosis: A systematic review of 13 observational studies. PLOS Medicine, 5(7), e152.
Koch, R. (1882). Die Aetiologie der Tuberculose. Berliner Klinische Wochenschrift, 19, 221–230.
Lawn, S. D., & Zumla, A. I. (2011). Tuberculosis. The Lancet, 378(9785), 57–72.
Light, R. W. (2010). Update on tuberculous pleural effusion. Respirology, 15(3), 451–458.
Mitchison, D. A. (1985). The action of antituberculosis drugs in short-course chemotherapy. Tubercle, 66(3), 219–225.
Murray, P. R., Rosenthal, K. S., & Pfaller, M. A. (2021). Medical microbiology (9th ed.). Elsevier.
Nunn, A. J., Phillips, P. P. J., Meredith, S. K., Chiang, C. Y., Conradie, F., Convery, C., … Gillespie, S. H. (2019). A trial of a shorter regimen for rifampin-resistant tuberculosis. New England Journal of Medicine, 380(13), 1201–1213.
Pai, M., Denkinger, C. M., Kik, S. V., Rangaka, M. X., Zwerling, A., Oxlade, O., … Menzies, D. (2014). Gamma interferon release assays for detection of Mycobacterium tuberculosis infection. Clinical Microbiology Reviews, 27(1), 3–20.
Qin, Z. Z., Sander, M. S., Rai, B., Banu, S., Mao, T. E., Pai, M., & Das, J. (2019). Using artificial intelligence to read chest radiographs for tuberculosis detection: A multi-site evaluation of the diagnostic accuracy of three deep learning systems. Scientific Reports, 9(1), 15000.
Riley, R. L., Mills, C. C., O'Grady, F., Sultan, L. U., Wittstadt, F., & Shivpuri, D. N. (1962). Infectiousness of air from a tuberculosis ward. American Review of Respiratory Disease, 85, 511–525.
Russell, D. G. (2007). Who puts the tubercle in tuberculosis? Nature Reviews Microbiology, 5(1), 39–47.
Tameris, M. D., Hatherill, M., Landry, B. S., Scriba, T. J., Snowden, M. A., Lockhart, S., … McShane, H. (2013). Safety and efficacy of MVA85A, a new tuberculosis vaccine, in infants previously vaccinated with BCG. The Lancet, 381(9871), 1021–1028.
Thwaites, G. E., van Toorn, R., & Schoeman, J. (2009). Tuberculous meningitis: More questions, still too few answers. The Lancet Neurology, 8(9), 890.
Van Der Meeren, O., Hatherill, M., Nduba, V., Wilkinson, R. J., Muyoyeta, M., Van Brakel, E., … Tait, D. (2018). Phase 2b controlled trial of M72/AS01E vaccine to prevent tuberculosis. New England Journal of Medicine, 379(17), 1621–1634.
World Health Organization. (2013). Automated real-time nucleic acid amplification technology for rapid and simultaneous detection of tuberculosis and rifampicin resistance: Xpert MTB/RIF assay for the diagnosis of pulmonary and extrapulmonary TB in adults and children. WHO.
World Health Organization. (2022). Global tuberculosis report 2022. WHO.
World Health Organization. (2023). Global tuberculosis report 2023. WHO.

#Limpieza y Manipulación de Datos

**Explorar los valores nulos/faltantes/NA**
"""

# Cuantos valores faltantes hay por columna?
who.isna().sum()

# Explorar los valores faltantes en la columna iso2
who[who.iso2.isna()]

# Los valores NA se debe a que el iso2 de Namibia es "NA", y pandas lo tomo como un valor faltante
who.loc[who.country == "Namibia", "iso2"] = "NA"

# Las demas columnas de casos con valores faltantes van a tener un valor default de 0
who.fillna(0, inplace=True)

# Cuantos valores falantes hoy por columna en la tabla de pop?
pop.isna().sum()

# como puedo convertir columnas en filas utilizando Pandas?:: Existe la función melt()

who2 = who.melt(id_vars=["country", "iso2", "iso3", "year"])
who2.head(10)

# Crear una columna que contenga el genero (Masculino o Femenino)
# Crear una funcion de Python que contenga las reglas
def asignar_genero(valor):
  if "m" in valor:
    return "Masculino"
  else:
    return "Femenino"

who2["genero"] = who2["variable"].apply(asignar_genero)
who2.head(15)

# the method of diagnosis (rel = relapse, sn = negative pulmonary smear, sp = positive pulmonary smear, ep = extrapulmonary)
def asignar_metodo(valor):
  if "rel" in valor:
    return "relapse"
  elif "sn" in valor:
    return "negative pulmonary smear"
  elif "sp" in valor:
    return "positive pulmonary smear"
  elif "ep" in valor:
    return "extrapulmonary"
  else:
    return "to define"

who2["metodo"] = who2["variable"].apply(asignar_metodo)
who2.head()

# Age group (014 = 0-14 yrs of age, 1524 = 15-24, 2534 = 25-34, 3544 = 35-44 years of age, 4554 = 45-54, 5564 = 55-64, 65 = 65 years or older).
def asignar_grupoedad(valor):
  if "014" in valor:
    return "0-14"
  elif "1524" in valor:
    return "15-24"
  elif "2534" in valor:
    return "25-34"
  elif "3544" in valor:
    return "35-44"
  elif "4554" in valor:
    return "45-54"
  elif "5564" in valor:
    return "55-64"
  else:
    return "65+"

who2["grupoedad"] = who2["variable"].apply(asignar_grupoedad)
who2.head()

# remover la columna variable
who2.drop(columns=["variable"], inplace=True)

# renombrar la columna value a casos
who2.rename(columns={"value":"cases"}, inplace=True)

who2.head()

# Traer el dato de la poblacion total
df = pd.merge(who2, pop, on=["country", "year"], how="inner")
df.head(10)

# Como guardar la tabla "df" como un archivo csv
df.to_csv("tuberculosis.csv") # se guarda en la carpeta de la sesion
df.to_csv("/content/drive/MyDrive/Data/tuberculosis.csv") # se guarda en el drive

"""# Explorar datos con python"""

# recordemos que df son los datos de tuberculosis ordenados
df.head()

# Por genero
por_genero = df.groupby("genero", as_index = False)["cases"].sum()
por_genero["porcentaje"] = 100 * por_genero["cases"] / por_genero["cases"].sum()
por_genero.head()

# Por metodo
por_metodo = df.groupby("metodo", as_index=False)["cases"].sum()
por_metodo["porcentaje"] = 100 * por_metodo["cases"] / por_metodo["cases"].sum()
por_metodo.head()

# Por grupoedad
por_grupoedad = df.groupby("grupoedad", as_index=False)["cases"].sum()
por_grupoedad["porcentaje"] = 100 * por_grupoedad["cases"] / por_grupoedad["cases"].sum()
por_grupoedad.head()

# La cantidad de Paises afectados, Año de inicio y el año de finalizacion
print(f"Cantidad de Paises: {df.country.nunique()}") # nunique es lo mismo que un count(distinct)
print(f"El año de inicio es: {df.year.min()}")
print(f"El año de finalizacion es: {df.year.max()}")

"""Tasa de incidencia (por cada 100 mil habitantes) = 100,000 * casos nuevo / poblacion"""

# Tabla para calcular la incidencia
country_year = df.groupby(["country", "year"], as_index=False).agg({"cases":"sum", "population":"max"})
country_year["tasa_incidencia"] = 100_000 * country_year["cases"] / country_year["population"]
country_year.head(10)

# Tabla para calcular la tasa de incidencia POR AÑO
by_year = country_year.groupby("year", as_index=False).agg(
    {"cases":"sum", "population": "sum"}
)
by_year["tasa_incidencia"] = 100_000 * by_year["cases"] / by_year["population"]
by_year

import matplotlib.pyplot as plt # base de visualizacion en Python
import seaborn as sns # visualizaciones mas sencillas hechas sobre Matplotlib
import plotly.express as px # visualizaciones interactivas

# Crear nuestra primera visualizacion con seaborn
plt.figure(figsize=(10, 6))
sns.barplot(x="year", y="tasa_incidencia", data=by_year)
plt.title("Tasa de incidencia por año")
plt.xlabel("Año")
plt.ylabel("Tasa de incidencia")
# guardar la grafica en nuestro drive
plt.savefig("/content/drive/MyDrive/Data/grafica_incidencia.png")

# Crear grafica de barras con plotly
fig = px.bar(by_year, x="year", y="tasa_incidencia")
fig.show()
plt.savefig("/content/drive/MyDrive/Data/grafica_incidencia_barras.png")